CREATE TABLE sales (
  `index` INT PRIMARY KEY,
  `Order_ID` VARCHAR(100),
  `Status` VARCHAR(50),
  `Fulfilment` VARCHAR(50),
  `Sales_Channel` VARCHAR(50),
  `ship_service` VARCHAR(100),
  `Style` VARCHAR(100),
  `SKU` VARCHAR(100),
  `Category` VARCHAR(100),
  `Size` VARCHAR(50),
  `ASIN` VARCHAR(50),
  `Courier_Status` VARCHAR(100),
  `Qty` INT,
  `Currency` VARCHAR(10),
  `Amount` DECIMAL(10,2),
  `ship_city` VARCHAR(100),
  `ship_state` VARCHAR(100),
  `ship_postal_code` VARCHAR(20),
  `ship_country` VARCHAR(100),
  `promotion_ids` TEXT,
  `B2B` BOOLEAN,
  `fulfilled_by` VARCHAR(100)
);
